rootfs/rootfs/usr/local/etc/init.d/docker
With this patch it is possible to access your boot2docker vm remotely.
- stop you b2d
- add bridge interface to you boot2docker vm
- restart b2d
- add this to your profile
`$  sudo vi /var/lib/boot2docker/profile`
CERT_INTERFACES='eth0 eth1 eth2'
- restart docker daemon
$sudo /etc/init.d/docker restart
At your remote host you now can add certs and setup env
```
cd ~/.boot2docker/certs
cp -r boot2docker-vm boot2docker-vm-`hostname`
scp boot2docker-vm-`hostname` peter@mymaschine:/Users/peter/.boot2docker/certs
ssh user@myremotemachine
DOCKER_CERT_PATH=/Users/peter/.boot2docker/certs/boot2docker-vm-HOSTNAME
DOCKER_HOST=tcp://192.168.178.120:2376
docker images
```
Thanx
Peter
=> configure the number of cert interface

Dockerfile
Fixes a bug preventing folder share throw VirtualBox Guest Additions.
The virtual box provided for windows is the 4.3.20 and it doesn't work with guest additions 4.3.18.
=> Updates the VBOX version

Dockerfile
This was the source of my strange issues with the serial console that I was having trouble tracking down -- we're running getty twice on `ttyS0`! :dizzy_face:
=> Finally fix ttyS1! (no more hanky ttyS0 problems)

doc/WORKAROUNDS.md
Add workaround instructions if boot2docker-vm is already running
=> Update workaround instructions

rootfs/rootfs/etc/rc.d/automount
setting the partition type wasn't being done properly nor written to
disk.
Signed-off-by: António Meireles <antonio.meireles@reformi.st>
=> fix 'typo' in swap partition creation

README.md
See http://unix.stackexchange.com/a/181581 for the rationale behind this change.
Fixes https://github.com/boot2docker/boot2docker/issues/716
=> Add "eval" to every invocation of "boot2docker shellinit"

Dockerfile, README.md
Tested and verified to boot up, initialize Docker on AUFS, and run containers properly. :+1:
```console
docker@boot2docker:~$ docker info
Containers: 0
Images: 0
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: tmpfs
Dirs: 0
Execution Driver: native-0.2
Kernel Version: 3.18.9-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : 175488c - Mon Mar  9 16:17:41 UTC 2015
CPUs: 1
Total Memory: 3.868 GiB
Name: boot2docker
ID: 34TC:BZMZ:5D6H:YFZD:TVBQ:RZG7:V2QT:7PXM:6KTJ:P7MM:TX46:G5A5
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 15
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /var/lib/docker
docker@boot2docker:~$ docker run --rm hello-world
Unable to find image 'hello-world:latest' locally
511136ea3c5a: Pull …
```
=> Bump the kernel to 3.18.9 (and AUFS patches to latest 3.18.1+)

Dockerfile, rootfs/make_iso.sh
Now that `jessie` is officially stable, let's make the switch! :+1:
This includes a few minor fixes to things that broke after switching, but the final ISO built from this branch was a success. :metal:
=> Finally switch the base to debian:jessie

rootfs/rootfs/etc/rc.d/install-ca-certs
I ran into this while trying out the instructions in the README. This change was required so that it will read the file correctly and handle the linking.
Fixes #873
=> Fix install-ca-files to use basename, not path

Dockerfile, rootfs/rootfs/etc/rc.d/automount
In some cases, kernel does not re-read partition table in time after fdisk changes.
The following mkswap/mkfs gets failure and complains that the partition does not exist.
This commit adds partprobe operations to fix this issue. Thanks!
=> automount: add partprobe operations to sync partition changes

rootfs/rootfs/usr/local/etc/init.d/docker
the cert generation script currently doesn't support interfaces with multiple IPs assigned.
=> support interfaces with aliases

Dockerfile
Source open-vm-tools from a branch that has Linux Kernel 4.x fixes for vmhgfs.
This fixes:
docker/machine#641
docker/machine#1275
docker/machine#1344
=> Fix Shared Folders on Linux Kernel 4.x

README.md, doc/FAQ.md
Previously it was easy to not realise that data outside of `/var/lib/docker` and `/var/lib/boot2docker` would be lost after reboots of the VM. We now also link to the relevant FAQ section from the main README, so it's easier to work out how to make permanent modifications.
Fixes #912.
=> Docs: Make VM data persistence (or lack of) clearer

Dockerfile
This uses the same mechanism as used by the aufs-util build on [line 104](https://github.com/boot2docker/boot2docker/blob/master/Dockerfile#L104) of the Dockerfile.
Fixes #826
=> Install kernel headers for Hyper-V KVP build to /tmp/kheaders

rootfs/rootfs/bootscript.sh
The files don't exist by default, so it's easy to forget to set the execute bit after creating them. Let's just be nice and source the files so they still run regardless.
*Edit: Changed to use /bin/sh instead*
Fixes #915.
=> Use /bin/sh to run bootlocal.sh/bootsync.sh in case execute bit not set

Dockerfile, rootfs/rootfs/bootscript.sh, rootfs/rootfs/etc/rc.d/xedaemon
This PR adds golang-based XenServer guest tools to boot2docker.
The guest tools are mandatory to:
* Enable the hypervisor to find out the IP address of the VM (as for example required by Docker Machine)
* Migrate the running VM between multiple hosts in a pool
Would appreciate feedback, questions, testing/review, error-reports - and a merge, once it's proven.
Signed-off-by: Phus Lu <phus.lu@citrix.com>
=> Add XenServer guest tools to boot2docker

rootfs/rootfs/etc/rc.d/automount
The sequence `(echo t; echo 2; echo 82; echo w) | fdisk $UNPARTITIONED_HD` to set the partition type for the swap partition to 82/Linux swap in the `/etc/rc.d/automount` script currently fails to do so because it doesn't match the commands that actually have to be entered.
Apparently when there's only 1 partition fdisk already selects this partition:
```
fdisk /dev/sda
...
Command (m for help): t
Selected partition 2
Hex code (type L to list codes):
```
No clue how long this hasn't been working correctly, but I couldn't find anything in the busybox release notes mentioning a change in fdisk behaviour related to this.
`fdisk -l` pre this fix
```
boot2docker ssh fdisk -l
Disk /dev/sda: 104.8 GB, 104857600000 bytes
255 heads, 63 sectors/track, 12748 cylinders
Units = cylinders of 16065 * 512 …
```
=> Fix setting swap partition type during automount

Dockerfile, rootfs/rootfs/bootscript.sh, rootfs/rootfs/etc/rc.d/prltoolsd
This PR adds a support of Parallels Tools, guest additions for Parallels Desktop for Mac.
In Dockerfile there is a link to an official build of Parallels Tools for Boot2Docker, supported by Parallels. We are going to keep it up-to-date and are ready to be responsible for Parallels Tools compatibility with the latest Boot2Docker version. 
Parallels Tools in bot2docker.iso are required to make Docker Machine compatible with Parallels Desktop for Mac: https://github.com/docker/machine/pull/939
Currently we have to use a custom build of boot2docker.iso: https://github.com/Parallels/boot2docker/releases/tag/v1.7.0-prl-tools
Features available in Boot2Docker with Parallels Tools:
- Parallels Shared Folders (`prl_fs` filesystem support);
- Graceful shutdown (by `prltoolsd`);
- Virtual network …
=> Add Parallels Tools support

Dockerfile, rootfs/rootfs/usr/local/etc/init.d/docker
Fix #808 and SvenDowideit/generate_cert#10. Update `generate_cert` to 0.2 (to gain access to the `--org` command line option). Use `--org` command line option to ensure org for automatically-generated CA cert differs from org for automatically-generated client/server certs. Work-around for OpenSSL bug (see <http://tinyurl.com/pqgnb2a>).
Merge needed for (i.e., blocks):
* docker/compose#890
* docker/docker-py#465
* possibly others
--
The Author grants to the owners of this repository, and the owners of the software it contains known as "boot2docker" (the Software), as well as their heirs and assigns (the Recipients), a perpetual and transferable license to all rights the Author may have to any material submitted in this pull request as if it were created by the Recipients themselves. By …
=> READY FOR REVIEW - work around OpenSSL issue which mistakes a cert as self-signed if CA org == cert org

rootfs/rootfs/usr/local/etc/init.d/docker
Replace the deprecated `-d` command line flag with the new command name `daemon`.
See https://github.com/docker/docker/pull/13771 for details.
=> use new 'daemon' command

doc/WORKAROUNDS.md
To allow access from LAN bind to 0.0.0.0 is needed this is done using *: prefix to -L
=> Fix temporary SSH line to allow access from LAN

rootfs/rootfs/etc/rc.d/ntpd
Fixes #840
From the `ntpd` man page: 
-g: Normally, ntpd exits with a message to the system log if the offset exceeds the panic threshold, which is 1000 s by default. This option allows the time to be set to any value without restriction; however, this can happen only once. If the threshold is exceeded after that, ntpd will exit with a message to the system log. This option can be used with the -q and -x options. See the tinker command for other options.
=> ntpd now updates system time regardless of offset

rootfs/rootfs/etc/rc.d/ntpd
Reverts boot2docker/boot2docker#1035
Oops: (https://github.com/boot2docker/boot2docker/pull/1035#issuecomment-131891255)
```console
docker@boot2docker:~$ sudo ntpd --help
BusyBox v1.23.1 (2015-02-22 15:53:49 UTC) multi-call binary.
Usage: ntpd [-dnqNw] [-S PROG] [-p PEER]...
NTP client/server
-d	Verbose
-n	Do not daemonize
-q	Quit after clock is set
-N	Run at high priority
-w	Do not set time (only query peers), implies -n
-S PROG	Run PROG after stepping time, stratum change, and every 11 mins
-p PEER	Obtain time from PEER (may be repeated)
If -p is not given, read /etc/ntp.conf
```
=> Revert "ntpd now updates system time regardless of offset"

Dockerfile
This update should fix the issues seen in #1055. The `openssl.tcz` extension contains OpenSSL 1.0.2d while the `openssl-1.0.0.tcz` extension contains OpenSSL 1.0.0k.
=> Use openssl.tcz instead of openssl-1.0.0

rootfs/rootfs/etc/rc.d/automount-shares
According to the document, it said that iocharset is default to utf8, however, actual behavior is not.
Force using utf8 to address the issue that non-ascii characters files disapper from the shared folders.
This is basically same as boot2docker/boot2docker#697 which is not updated since May, but doesn't change `mount -t vbox` to `mount.vbox` also keeps `defaults` option.
This will solve the issue similar to docker/machine#1763.
Closes boot2docker/boot2docker#697
=> Use iocharset=utf8 for automunt-shares

Dockerfile, Dockerfile.experimental
I updated all but one of the `curl` commands in the `Dockerfile` to fail fast. The only one I didn't update is the one that fetches the kernel sources since it uses `--retry`, which doesn't play nice with `-f`.
=> Use curl -f to fail on non-2XX HTTP status codes

Dockerfile, rootfs/rootfs/etc/rc.d/vmtoolsd
- removed kernel module dependency
- FUSE-based shared folders
- moved to official github repository
This goes hand in hand with docker/machine#1816
This aims to also fix docker/machine#1460
=> Moving to VMware tools 10.x

Dockerfile
This is a build published with the current version of Parallels Desktop 11.
=> Update Parallels Tools to 11.0.1-31277

rootfs/rootfs/usr/local/etc/init.d/docker
When want you to know status of docker daemon with :
root@default:/etc/init.d# ./docker status
Docker daemon is not running
root@default:/etc/init.d#
But with ps, docker is running 
root@default:/etc/init.d# ps -ef | grep `cat /var/run/docker.pid`
root      1218     1  0 07:54 ?        00:00:00 /usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
root      1601  1324  0 08:12 pts/0    00:00:00 grep 1218
In function check()
ps -o pid | grep "^\s*$(cat /var/run/docker.pid)$" return false status of docker daemon
root@default:/etc/init.d# ps -o pid
PID
1324
1692
My solution …
=> docker daemon status not work correctly

Dockerfile
Due to #1054, the `extra` subdirectory is no longer created. I was too naive while putting Parallels kernel modules to this dir :-(
So, in v1.8.3 there are no kernel modules from Parallels Tools, which causes a critical issue with shared folder mounting: https://github.com/Parallels/docker-machine/issues/7
In this PR I've changed the path for storing kernel modules from Parallels: let them be in the top level dir, adjacent to vbox modules.
@tianon Please, review this PR. We looking forward to get it released ASAP :pray:
=> Hotfix: Parallels kernel modules are unavailable in v1.8.3

Dockerfile
There are no critical changes, but now this version could be built on Linux 4.2
=> Update Parallels Tools to 11.0.2-31348

rootfs/rootfs/bootscript.sh
Pretty much what it says on the tin. Ensure that the DHCP client reports the correct hostname.
=> Set hostname before starting DHCP client.

Dockerfile
Hi there!
Using Virtualbox shared folders and NFS we were never able to approach the performance we needed for our development environments, so we turned to rsync. (https://github.com/roverdotcom/docker-rsync/tree/rover)
Specifically:
- The vboxsf solution showed an 80%-100% slowdown relative to bare metal for application server reload & Python module loading when running our test suite.
- The NFS solution showed more like ~50% slowdowns for many tasks and our Django application often wouldn't detect filesystem changes either fast enough or at all.
By comparison, various metrics show either no slowdown or a ~10% slowdown relative to bare metal for the rsync solution.
Currently, the rsync solution requires running `tce-load -wi rsync attr acl` on each restart which creates a dependency on …
=> Add rsync and dependencies

Dockerfile
This should fix docker/docker#18180.
http://permalink.gmane.org/gmane.linux.file-systems.aufs.user/5345
=> Update AUFS to v4.1.13+-20160111

Dockerfile
Update #1111 (fixes the issue(2): `/dev/disk/by-id` appears now)
=> Add udev-extra

README.md
https://github.com/boot2docker/boot2docker/blob/master/README.md#tls-support
=> Docker only supports TLS

rootfs/rootfs/usr/local/etc/init.d/docker
Starting in docker 1.10, a persistent configuration file can be stored
(/etc/docker/daemon.json).  This change makes sure that we store
/etc/docker on the mounted filesystem so it will survive reboots.
=> Persist /etc/docker directory

rootfs/rootfs/usr/local/etc/init.d/docker
Docker daemon takes forever and a half to exit (about 10s on a
fresh boot2docker 1.10 VM). Attempting to restart before it is
stopped just fails miserably: start aborts and stop eventually
completes.
Arguably start and stop should only return once the daemon is
actually started/stopped but that might impose undue delay on
callers that only care about an eventual state change and are
unmoved by the prospect of race conditions.
=> Fix /etc/init.d/docker restart

rootfs/rootfs/etc/rc.d/automount
We've been encountering regular inode exhaustion with boot2docker/docker-machine. It seems like this is a problem that is likely to be affecting more and more people with the gradual convergence on overlayfs. 
I'd hoped to be able to pass a parameter somehow to the `automount` script, I guess via a kernel boot parameter? That would address #992. I couldn't figure out a way to do that, any suggestions?
=> Use a higher ratio of inodes to address inode exhaustion in overlayfs

Dockerfile, rootfs/rootfs/usr/local/etc/init.d/docker
This includes a modification to the `Dockerfile` to get the new `docker-*` binaries, and a patch to the `/etc/init.d/docker` script which fixes a newly unearthed race condition in `docker-machine` / `/etc/init.docker/stop`.
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>
=> Add support for Docker 1.11.0-rc1

rootfs/rootfs/etc/rc.d/install-ca-certs
Although it's conventional for cert file names to use underscores and not spaces, this fix allows `/etc/rc.d/install-ca-certs` to work if `/var/lib/boot2docker/certs` names do contain spaces.
=> Allow spaces in certificate file names

Dockerfile.experimental
The experimental dockerfile was very outdated; we had been using a custom Dockerfile on the build server for the experimental iso.  Now it can be more clear how it is built.
Fixes #1192
=> Update Dockerfile.experimental from Dockerfile

rootfs/rootfs/etc/rc.d/install-ca-certs
The [official Docker docs on creating a self-signed certificate](https://docs.docker.com/registry/insecure/#using-self-signed-certificates) use a `.crt` extension for the public PEM certificate. To help users that are following those documents, it would help to also accept that extension in this script, as well.
=> Also process certificates with the .crt extension.

README.md
Document method more inline with Docker Engine to add registry certs as suggested at https://github.com/boot2docker/boot2docker/pull/1167#issuecomment-226218581.
Fix #347
Related to https://github.com/docker/machine/issues/2247, https://github.com/docker/machine/issues/1799, https://github.com/docker/machine/issues/1963, https://github.com/docker/machine/issues/1872, https://github.com/docker/machine/pull/3690, https://github.com/docker/toolbox/pull/558
=> document better way to add registry certificates

Dockerfile
Parallels Desktop 12 has been released in August 2016. This PR upgrades Parallels Tools for Boot2Docker up to the latest version (v12.1.0)
Issue #1164 should be fixed there. 
I have verified the build from this branch - everything works fine.
=> Upgrade Parallels Tools to v12.1.0

Dockerfile, Dockerfile.experimental
- addresses issues where build on the hub fails, such as #1209
- uses workaround based on docker/hub-feedback#811
=> workaround instead of adding files to /

rootfs/rootfs/etc/rc.d/vbox
It seems like VBoxControl does work with the current version, so all I had to do is listing the shared folders with it, and mount them.
Related to: https://github.com/docker/machine/pull/3798
=> Mount all VirtualBox shared folders by listing them with VBoxControl

rootfs/rootfs/usr/local/etc/init.d/docker
cc @yosifkit @nathanleclaire
See also https://github.com/docker/docker/issues/28368 (`docker daemon` sometimes broken in 1.13.0-rc1)
=> Update "docker daemon" to simply "dockerd" ("docker daemon" is officially deprecated in 1.13+)

doc/BUILD.md
`make_iso.sh` lives in `/tmp` now, not `/`.
See https://github.com/boot2docker/boot2docker/blob/master/Dockerfile#L369
=> Correct the path to make_iso.sh

Dockerfile, rootfs/rootfs/usr/local/bin/autologin, rootfs/rootfs/usr/local/bin/forgiving-getty
Closes #1221
Closes: docker/machine#3711
cc @nathanleclaire @jonathanperret @simonvanderveldt
=> Add new "forgiving-getty" wrapper which verifies that a given TTY is actually a TTY before spawning getty on it (repeatedly)

rootfs/rootfs/etc/rc.d/install-ca-certs
While `install-ca-certs` allows for either `pem` or `crt` files, if no `pem` file is found it will attempt to install `*.pem` which more than likely doesn't exist. This causes a failure when installing a new `crt` file (i.,e., `corporate.crt`) when there are no `pem` files found.
This change simply checks whether `$cert_file` exists and if not, it continues to the next loop iteration.
=> Only attempt to install cert files if they exist

Dockerfile
Previously prl_fs didn't provide fsync handler for directory operations
(but for files did). As a result respective syscalls failed. That
caused, for example, problems with running PostgreSQL in containers over
database on a shared volume.
This patch is really a kludge to workaround the issue. And should be
removed when Parallels Tools with fixed prl_fs is incorporated.
Parallels/docker-machine-parallels#71
=> Fix fsync on dirs in Parallels Shared Folders

rootfs/rootfs/usr/local/etc/init.d/docker
Removes the `-D` flag from `dockerd` so that users can optionally add this either via `daemon.json` or via `--engine-opt`.
Closes #1297
=> Remove -D default debug option

Dockerfile
Parallels Desktop v13.3.0 has been recently released. Guest tools for boot2docker were published too.
@romankulikov Can the fix from https://github.com/boot2docker/boot2docker/pull/1294 be reverted, after merging this Pull-Request?
=> Upgrade Parallels Tools to 13.3.0-43321

kernel_config
Looks like `CONFIG_IPVLAN=m` was (inadvertently?) [removed](https://github.com/boot2docker/boot2docker/commit/5ad3cc8591eb010e36971946076c908aeb988df4#diff-42196f7da8f6fcbf138d1f56a53afb8fL2027) in 5ad3cc859.  I'm guessing that this was due to the introduction of `CONFIG_NET_L3_MASTER_DEV` somewhere in between `4.4.110` and `4.9.86` to support [this kernel changeset](https://github.com/torvalds/linux/commit/4fbae7d83c98c30efcf0a2a2ac55fbb75ef5a1a5); apparently `CONFIG_IPVLAN` now depends on this setting being enabled (see, e.g., [this RedHat bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1428530)).
Thanks in advance for your consideration!
=> Restore CONFIG_IPVLAN=m to kernel configuration

Dockerfile
The currently bundled version of open-vm-tools has an issue where only 16 IPs are going to be reported to the vmware hypervisor, and the link local IP addresses of veth* NICs are included. The end result is that if you start up a large compose file, the VM's own IP will be pushed out of the reported guest IPs list, and commands such as `docker-machine env` and `docker-machine ip` will hang.
See vmware/open-vm-tools#100
=> Update open-vm-tools to 10.2.5-8068406

rootfs/rootfs/usr/local/etc/init.d/docker
Closes https://github.com/boot2docker/boot2docker/issues/1326
=> Explicitly ignore requests for AUFS (since they'll just fail to start dockerd anyhow)

Dockerfile, files/init.d/docker, files/udhcpc.patch
This primarily appears to happen because we have two networks and run DHCP on both, resulting in a cleared out `/etc/resolv.conf` _sometimes_ (depending on which DHCP response our VM processed last).
This is as noted in https://github.com/boot2docker/boot2docker/pull/1343#issuecomment-436451793.
=> Add two separate solutions to the "empty resolv.conf" issue

files/kernel-config.d/tun
Readd tun/tap support to kernel which was removed in c2b60ab21080d15148948fc6536078251dcfa842
With you latest update in c2b60ab21080d15148948fc6536078251dcfa842 you've removed the tun/tap support entirely - which is very bad if someone use the docker container with openvpn.
=> Add tun/tap support which is removed now

files/make-b2d-iso.sh
Fixes #1347
```console
$ isoinfo -d -i boot2docker.iso
CD-ROM is in ISO 9660 format
System id: 
Volume id: b2d-v18.09.0
Volume set id: 
Publisher id: 
Data preparer id: XORRISO-1.4.6 2016.09.16.133001, LIBISOBURN-1.4.6, LIBISOFS-1.4.6, LIBBURN-1.4.6
Application id: BOOT2DOCKER
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 23040
El Torito VD version 1 found, boot catalog is in sector 49
NO Joliet present
Rock Ridge signatures version 1 found
Eltorito validation header:
Hid 1
Arch 0 (x86)
ID ''
Key 55 AA
Eltorito defaultboot header:
Bootid 88 (bootable)
Boot media 0 (No Emulation Boot)
Load segment 0
Sys type 0
Nsect 4
Bootoff 32 50
```
=> Fix volume ID for docker-machine

files/make-b2d-iso.sh
I've personally tested this successfully with https://github.com/machine-drivers/docker-machine-driver-xhyve/releases/tag/v0.3.3. :+1:
Fixes #1355
Refs https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/211
=> Drop "-partition_offset" from "xorriso" invocation to fix xhyve / Mac OS mounting the ISO

files/udhcpc.patch
This might help with #1366 and should help with #1330 (by allowing DHCP values to overwrite the default provided NTP configuration).
=> Adjust DHCP to be slightly less asynchronous, to log to /var/log/dhcp.log, and to apply NTP servers from DHCP to our local configuration

files/kernel-config.d/networking, files/kernel-config.d/tun
Closes #1384
It was tempting to also combine `ebpf` into this file, but I think the scope of eBPF in general is much larger than networking.
=> Add "CONFIG_NET_SCH_NETEM" for network delay/loss emulation

files/init.d/haveged
See https://bugs.debian.org/923675#72; essentially if we have hardware RNG of some type, skip software RNG, otherwise check whether we have enough entropy to maybe not bother.
The latter part of this check probably isn't strictly necessary (it should be reasonably harmless to start haveged in all cases of missing hardware RNG), but we're a little different from the debian-installer use case.  In d-i, they're only talking about starting `haveged` for the duration of the installation process, where the instance we start will potentially affect our users more directly (more akin to if they were discussing adding `haveged` to the default set of installed packages where hardware RNG does not exist, so we want to be a tad bit more conservative about where/when we apply this).
=> Adjust conditional "haveged" startup according to bwh's suggestion for d-i

Dockerfile, files/init.d/vbox, update.sh
This reverts commit b5def189c5a5b577387090671651f5dee9576fde (#1396).
Fixes https://github.com/boot2docker/boot2docker/issues/1398
=> Pin VBoxGuestAdditions to 5.x (revert VBoxControl changes)

Dockerfile, files/tce-load.patch, update.sh
For some reason, the latest 4.4 upload of squashfs-tools in TCL 10.x fails to extract many/most .tcz files from TCL.  On the flip side, it's really easy to compile statically and the `Dockerfile` is much cleaner, so we're going with it.
=> Swap TCL's squashfs-tools for a static compiled version instead
