boot2docker/boot2docker

- Dockerfile
https://lwn.net/Articles/631319/
Tested and working. :+1:
> Bump kernel to 3.18.5

- README.md
> fix kernel version listed as released in 1.5.0

- README.md
So you don't have to log-in via SSH, run commands and log out.
> Simplifying insecure registry setup.

- doc/WORKAROUNDS.md
This doesn't allocate a pseudo-tty and gives a nice foreground log of connections being made.
> Nicer boot2docker ssh example

- doc/FAQ.md
- rootfs/rootfs/bootscript.sh
> Allow user customisation before and after Docker daemon startup

- Dockerfile
- README.md
Also, bump AUFS patches while we're at it.
> Bump kernel to 3.18.10

- rootfs/rootfs/bootscript.sh
> lets remove the please format me file properly

- doc/FAQ.md
> Document the version mismatch error, and how to solve it

- rootfs/rootfs/usr/local/etc/init.d/docker
Fixed the docker init script so that when pid file exist and the process is gone, the check fails.
> Fail check if process is gone.

- Dockerfile
- kernel_config
- rootfs/rootfs/etc/rc.d/vmtoolsd
- rootfs/rootfs/usr/local/etc/init.d/docker
rebased #748
and starting to test
> Tcl6 64 bit userspace

- Dockerfile
- README.md
- kernel_config
I'm very disappointed in the lack of "Not Found" jokes for this kernel version in the posts and articles I can find about this kernel version.
> Update to Linux 4.0.4

- doc/WORKAROUNDS.md
> Note about UDP port forwarding

- Dockerfile
protect against #871 happening again
closes #871
> Ensure that ncurses does not accidentally get optimised out

- README.md
>  Docs to cover usage of boot2docker profile

- Dockerfile
- README.md
Fixes #902
AUFS changes: https://github.com/sfjro/aufs4-standalone/compare/e004c948c714de6c709161a9d32ab4546063cdb6...a8c8a849e236d7f7fa121c8344899a796ccf7b8f
> Update kernel and AUFS

- Dockerfile
Let's get a tiny bit more consistency and repeatability here. :+1:
> Update Dockerfile to be explicit about dependencies

- Dockerfile
- README.md
- kernel_config
See https://lwn.net/Articles/649742/ :+1: (lol@https://github.com/boot2docker/boot2docker/pull/963)
> Update kernel to 4.0.7

- README.md
- doc/WORKAROUNDS.md
Hey guys,
This lists some workarounds I've seen for users impacted by #824, #938  and #606. I'm happy to update them based on better solutions.
Also, would it make sense to update the verbiage in this [page](https://github.com/boot2docker/boot2docker/releases/tag/v1.7.0) to include warnings and formally listing known issues? Lots of people are upgrading and seeing connection issues.
Thanks,
Michael
> Adds connection issue workarounds and link in readme.

- Dockerfile
- rootfs/rootfs/bootscript.sh
- rootfs/rootfs/etc/rc.d/vbox
> Add VBoxService and use it for timesync!

- Dockerfile
- README.md
cc @frapposelli @legal90 @phusl -- anything objections to making this move?  Any additional changes we'll need to make that you're aware of?
> Update to Linux 4.1

- Dockerfile
> Add /etc/timezone and /etc/localtime specifically for bind-mounting oneliners

- README.md
Fixed formatting to style matched steps one and two of delete/create VM.
Switched "changes" --> "change" as only one change is mentioned.
> grammar and formatting

- rootfs/rootfs/etc/rc.d/ntpd
cc @nathanleclaire
I also tested manually setting my system clock to 1970-01-01, and this script as-is kicked me to the correct current time within a few iterations, but it might be worth splitting that out so the script blocks until the time is set, then backgrounds.  Hoping for some opinions on that. :smile:
Fixes #736
> Refactor ntpd to support multiple servers

- rootfs/rootfs/etc/rc.d/sshd
> Fix typo in /etc/rc.d/sshd

- rootfs/rootfs/etc/rc.d/automount
pretty self explanatory, just wait for the block devices to exist before attempting to format them
> wait for disks to actually exist, closes #793

- Dockerfile
Fixes #1144
cc @nathanleclaire; I've tested this locally and it seems to work properly -- containers start up, etc, SSH works, but I think it warrants testing with `docker-machine` before we really commit :+1:
> Update to TCL 7.0

- Dockerfile
Fixes #1157
Signed-off-by: Fabio Rapposelli <fabio@vmware.com>
> Add dummy link to libtirpc to fix vmhgfs-fuse

- Dockerfile
This allows us to run binaries like "vmhgfs-fuse" and verify that at the very least all the ".so" files they need are discoverable.  (Which is really important for helping us avoid issues like #1157 in future updates.)
cc @nathanleclaire @frapposelli
> Reorganize the Dockerfile a bit (for caching, but also for testability)

- README.md
Cleanup docs to reference Docker Toolbox and Machine where appropriate rather than depreciated `boot2docker` CLI tool.
> update docs with docker toolbox & machine details

- README.md
Docs for https://github.com/boot2docker/boot2docker/pull/1167
> Add .crt support to docs

- rootfs/rootfs/etc/rc.d/vbox
cc @yosifkit @nathanleclaire 
Follow-up for https://github.com/boot2docker/boot2docker/pull/1088
> Update some minor try_mount_share assumptions (assumes root-relative via cwd)

- Dockerfile
I officially dedicate this PR to @nathanleclaire.
(someday I hope to be a unicorn, just like this little rhino does)
> Add SHA256 verification to our VBoxGuestAdditions.iso fetching

- rootfs/rootfs/etc/rc.d/sshd
in /etc/rc.d/sshd script
Fixes #1172
> Fix ssh/sshd sample config file names

- Dockerfile
I have verified the build from this branch - everything works fine.
> Upgrade Parallels Tools to v12.1.3

- Dockerfile.master
This is officially dedicated to @nathanleclaire, who always has interesting problems. :+1:
> Add "Dockerfile.master" for creating ISO builds based on the artifacts from master.dockerproject.org

- Dockerfile
Fixes #1342
Thanks for testing and reporting, @luo12yan! :heart:
> Fix vboxsf.ko inclusion (fixes VirtualBox shared folders)

- Dockerfile
- files/kernel-config.d/virtualbox
> Re-add support for the "LsiLogic SAS Controller" in VirtualBox

- files/init.d/vbox
> Fix VBoxControl usage ("--automount")
